algoritmo "resultado"
// Função :
// Autor :
// Data : 01/04/2026
// Seção de Declarações 
var
n1 , n2 , adicao : real
inicio
Escreva("Digite o valor do primeiro número : " )
Leia(n1)
Escreva("Digite o segundo número : " )
Leia(n2)
adicao<-n1+n2
se(adicao<30)entao
  Escreval("O resultado deu menor do que trinta ")
senao
  se(adicao>30)entao
  Escreval("O resultado deu maior do que trinta " )
  fimse
fimse
fimalgoritmo
