algoritmo "produto"
// Função :
// Autor :
// Data : 19/03/2026
// Seção de Declarações 
var
nome : caracter
quancomprada , precounitario , total : real
inicio
Escreva("Digite o nome do produto : " )
Leia(nome)
Escreva("Digite a quantidade que foi comprada : " )
Leia(quancomprada)
Escreva("Digite o valor do preço unitário  : " )
Leia(precounitario)
total<-quancomprada*precounitario
Escreva("O produto é : " , nome , " e o valor total é de : " , total)
fimalgoritmo
