algoritmo "altura"
// Função :
// Autor :
// Data : 02/04/2026
// Seção de Declarações 
var
nome1 , nome2 : caracter
altura1 , altura2 : real
inicio
Escreva("Digite o nome da primeira pessoa : " )
Leia(nome1)
Escreva("Digite o nome da segunda pessoa : " )
Leia(nome2)
Escreva("Digite a altura da primeira pessoa : " )
Leia(altura1)
Escreva("Digite a altura da segunda pessoa : " )
Leia(altura2)
se(altura1>altura2)entao
  Escreval(nome1 , "é maior que " , nome2)
senao
  se(altura2>altura1)entao
    Escreval(nome2 , " é maior que " , nome1 )
    fimse
fimse
fimalgoritmo
