algoritmo "compras"
// Função :
// Autor :
// Data : 31/03/2026
// Seção de Declarações 
var
total , quan_comprada , precounitario : real
nome: caracter
inicio
Escreva("Digite o nome do produto : " )
Leia ( nome)
Escreva("Digite a quantidade comprada : " )
Leia(quan_comprada)
Escreva("Digite o preço unitário do produto : " )
Leia(precounitario)
total<-quan_comprada*precounitario
Escreval("O nome do produto é : " , nome)
Escreval("O total é de : " , total )
fimalgoritmo
