algoritmo "dobroEtriplo"
// Função :
// Autor :
// Data : 04/03/2026
// Seção de Declarações 
var
dobro , triplo , numero1 , numero2 :inteiro
inicio
Escreva("Digite o primeiro número : " )
Leia(numero1)
Escreva("Digite o segundo número : " )
Leia(numero2)
dobro<-numero1*2
triplo<-numero2*3
Escreval("O dobro do primeiro número é : ", dobro )
Escreva("O triplo do segundo número é :  ", triplo )
fimalgoritmo
