algoritmo "ASDM"
// Função :
// Autor :
// Data : 04/03/2026
// Seção de Declarações 
var
adicao , subtracao , multiplicacao , divisao , numero1 , numero2 : real
inicio
Escreva("Digite o primeiro número:")
Leia(numero1)
Escreva("Digite o segundo número:")
Leia(numero2)
adicao<-numero1+numero2
Escreva("O resultado da adição é : " , adicao)
subtracao<-numero1-numero2
Escreva("Digite o primeiro número:")
Leia(numero1)
Escreva("Digite o segundo número:")
Leia(numero2)
Escreva("O resultado da subtração é : " , subtracao)
Escreval("Digite o primeiro número:")
Leia(numero1)
Escreva("Digite o segundo número:")
Leia(numero2)
multiplicacao<-numero1*numero2
Escreva("O resultado da multiplicação é : " , multiplicacao)
Escreval("Digite o primeiro número:")
Leia(numero1)
Escreva("Digite o segundo número:")
Leia(numero2)
divisao<-numero1/numero2
Escreva("O resultado da divisão é : " , divisao)

fimalgoritmo
