algoritmo "velho"
// Função :
// Autor :
// Data : 01/04/2026
// Seção de Declarações 
var
nome1 , nome2 : caracter
idade1 , idade2 : real
inicio
Escreva("Digite o nome da primeira pessoa : " )
Leia(nome1)
Escreva("DIgite o nome da segunda pessoa : " )
Leia(nome2)
Escreva("Digite a idade da primeira pessoa : ")
Leia(idade1)
Escreva("Digite a idade da segunda pessoa : ")
Leia(idade2)
se(idade1>idade2)entao
  Escreval(nome1 , " é mais velho do que " , nome2)
senao
  se(idade1<idade2)entao
  Escreval(nome2 , "é mais velho do que " , nome1)
  fimse
fimse
fimalgoritmo
