algoritmo "mq"
// Função :
// Autor :
// Data : 01/04/2026
// Seção de Declarações 
var
quadrado , metade , n1 : real
inicio
Escreva("Digite o número : " )
Leia(n1)
se(n1<0)entao
  quadrado<-n1^2
  Escreval("O resultado do número negativo ao quadrado é : " , quadrado)
senao
  se(n1>0) entao
    metade<-n1/2
    Escreval("O resultado do número positivo dividido é de : " , metade)
    fimse
fimse
fimalgoritmo
