algoritmo "nasc"
// Função :
// Autor :
// Data : 17/03/2026
// Seção de Declarações 
var
nome : caracter
idade , anonascimento , anoatual: real
inicio
Escreva("Digite o nome da pessoa :")
Leia(nome)
Escreva("Digite o ano de nascimento da pessoa :")
Leia(anonascimento)
Escreva("Digite o ano atual: " )
Leia(anoatual)
idade<-anoatual-anonascimento
Escreva(nome, "a sua idade é " , idade)

fimalgoritmo
