algoritmo "NomeePeso"
// Função :
// Autor :
// Data : 25/03/2026
// Seção de Declarações 
var
 nome1 , nome2 : caracter
 Peso1 , peso2 : real
inicio
Escreva("Digite o nome da primeira pessoa : " )
leia(nome1)
Escreva("Digite o nome da sugunda pesoa : " )
Leia(nome2)
Escreva("Digite o peso da primeira pessoa : " )
leia(peso1)
Escreva("Digite o peso da segunda pessoa : " )
Leia(peso2)
se (peso1 > peso2 ) entao
  Escreval(nome1 , " é mais pesado que " , nome2)
  Escreval("O peso é de " , peso1 )
senao
  se(peso1<peso2) entao
    Escreval(nome2 , " é mais pesado que " , nome1)
    Escreval("O peso é de " , peso2)
  fimse
fimse
fimalgoritmo
