algoritmo "semnome"
// Função :
// Autor :
// Data : 01/04/2026
// Seção de Declarações 
var
nome1 , nome2 : caracter
 peso1 , peso2 : real
inicio
Escreva("Digite o nome da primeira pessoa : " )
Leia(nome1)
Escreva("Digite o nome da segunda pessoa : " )
Leia(nome2)
Escreva("Digite o peso da primeira pessoa : ")
Leia(peso1)
Escreva("Digite o peso da segunda pessoa : " )
Leia(peso2)
se(peso1<peso2)entao
  Escreval(nome1 , " tem um peso maior em comparação com a/o " , nome2 )
senao
  se(peso2<peso1)entao
  Escreval(nome2 , " tem um peso maior em comparação com a/o " , nome1 )
  fimse
fimse
fimalgoritmo
