algoritmo "MetadeOuQuadrado"
// Função :
// Autor :
// Data : 25/03/2026
// Seção de Declarações 
var
n1 , metade , quadrado : real
inicio
Escreva("Digite o número : " )
Leia(n1)
Escreval("O valor do número é de : " , n1 )
se(n1>0) entao
metade<-n1/2
  Escreval("O resultado é de : " , metade)
senao
  se (n1<0) entao
quadrado<-n1*n1
    Escreval("O resultado é de : " , quadrado)
  fimse
fimse
fimalgoritmo
