algoritmo "perimetro e area"
// Função :
// Autor :
// Data : 31/03/2026
// Seção de Declarações 
var
area , perimetro , a , b : real
inicio
Escreva("Digite o valor do lado A : " )
Leia(a)
Escreva("Digite o valor do lado B : " )
Leia(b)
area <- a * b
perimetro <-  2* a + 2* b
Escreval("O valor da área do retângulo é de : " , area)
Escreval("O valor da perímetro do retângulo é de : " , perimetro)
fimalgoritmo
