algoritmo "ASDM"
// Função :
// Autor :
// Data : 04/03/2026
// Seção de Declarações 
var
adicao , subtracao , multiplicacao , divisao , numero1 , numero2 : real
inicio
Escreva("Digite o primeiro número:")
Leia(numero1)
Escreva("Digite o segundo número:")
Leia(numero2)
adicao<-numero1+numero2
subtracao<-numero1-numero2
multiplicacao<-numero1*numero2
divisao<-numero1/numero2
Escreval("O resultado da adição é : " , adicao)
Escreval("O resultado da multiplicação é : " , multiplicacao)
Escreval("O resultado da divisão é : " , divisao)
Escreval("O resultado da subtração é : " , subtracao)
fimalgoritmo
