algoritmo "somaSe"
// Função :
// Autor :
// Data : 25/03/2026
// Seção de Declarações 
var
adicao , n1 , n2 : real
inicio
Escreva("Digte o valor do primeiro número : " )
Leia(n1)
Escreva("Digite o valor do segundo número : " )
Leia(n2)
adicao<-n1+n2
Escreval("O resultado da soma é de : " , adicao )
se (adicao > 30 ) entao
  Escreval(" O resultado é maior do que 30 " )
senao
  se(adicao < 30 ) entao
    Escreval(" O resultado é menor do que 30 " )
  fimse
fimse
fimalgoritmo
